import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import NavBar from '@/comps/nav'
import MenuProp from '@/comps/menuPopUp'
import { Words } from '@/comps/words'

export default function About() {
  const [menuPopup, setMenuPopup] = useState(false)
  const [position, setPosition] = useState(0)

  function MenuPopUp(){
    menuPopup ? setMenuPopup(false) : setMenuPopup(true)
  }

  function HandleArrows(boolean){
    if(boolean){
      if(position == Words.indexOf(Words[Words.length-1])){
        setPosition(0)
      } else {
        setPosition(position+1)
      }
    } else {
      if(position == 0){
        setPosition(Words.indexOf(Words[Words.length-1]))
      } else {
        setPosition(position-1)
      }
    }
  }

  // useEffect(()=>{
  //   console.log(Words.indexOf(Words[Words.length-1]))
  // }, [])

  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="MDIA 2109"/>
        <meta property="og:title" content="Assignment #1 - About Us Page"/>
        <meta property="og:description" content="BCIT Digital Design and Development Diploma"/>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.mainAbout}>
        <NavBar onClick={()=>{MenuPopUp(true)}}></NavBar>
        {menuPopup && <MenuProp onClick={()=>{MenuPopUp(false)}}></MenuProp>}
        <div className={styles.flexboxRowAbout}>
          <hr noshade="true" className={styles.lineBreakAbout}/>
          <h1 className={styles.h1About}>About Us</h1>
          <hr noshade="true" className={styles.lineBreakAbout}/>
        </div>

        <div className={styles.flexboxColumnAbout}>
          <p>We are proud to deliver an education that goes beyond textbooks and classrooms.</p>
          <p>Our students gain the technical skills, real-world experience, and problem-solving ability needed to embrace complexity and lead innovation in a rapidly changing workforce.</p>
          <p>Through close collaboration with industry, our network of alumni and partners continue to achieve global success.</p>
          <h2 className={styles.h1}>Information Sessions</h2>
          <p>Information sessions are a simple way to figure out the next step along your career path. Learn more about the programs that interest you.</p>
          <h3>Big Info</h3>
          <p>Big Info is the largest program expo and information session at BCIT. It's your chancee to find out about all our programs - from business, computing, and health to engineering, trades, and applied sciences.</p>
          <p>If you missed our fall event the next Big Info is scheduled to return on February 15, 2023.</p>
          <h2 className={styles.h1}>Campus Tours</h2>
          <p style={{marginBottom:"50px"}}>Tours run weekdays September to May, on our Burnaby campus. See BCIT in person and get a taste of campus life.</p>
        </div>

        <div id='carouselImage' style={{backgroundImage:`url(/${position}.jpg)`}}>
          <img className="carouselArrow" src='/icons/leftArrow.png' onClick={()=>{HandleArrows(false)}}></img>
          <h4 id="testOnImageHere">{Words[position].value}</h4>
          <img className="carouselArrow" src='/icons/rightArrow.png' onClick={()=>{HandleArrows(true)}}></img>
        </div>

        <div className={styles.flexboxRowAbout}>
          <hr noshade="true" className={styles.lineBreakAbout}/>
          <h1 className={styles.h1About}>DEPARTMENTS</h1>
          <hr noshade="true" className={styles.lineBreakAbout}/>
        </div>
        <ul>
          <li>Applied & Natural Sciences</li>
          <li>Business & Media</li>
          <li>Computing & IT</li>
          <li>Engineering</li>
          <li>Health Sciences</li>
          <li>Trades & Apprenticeships</li>
        </ul>

        <a href="/">
          <span className={styles.arrowsAboutUp}>
            <img className={styles.arrowSize} src="/upwardArrow.png"/>
          </span>
        </a>
        <a href="/contact">
          <span className={styles.arrowsAbout} >
            <img className={styles.arrowSize} src="/downwardArrow.png"/>
          </span>
        </a>
      </main>
    </>
  )
}
