import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import NavBar from '@/comps/nav'
import MenuProp from '@/comps/menuPopUp'

export default function Contact() {
  const [menuPopup, setMenuPopup] = useState(false)
  const [firstName, setFirstName] = useState()
  const [lastName, setLastName] = useState()
  const [email, setEmail] = useState()
  const [appearButton, setAppearButton] = useState(false)

  const nameReg = /^[A-Z][A-Za-z ]{0,19}$/
  const emailReg = /^[a-zA-Z0-9.-_]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)$/


  function MenuPopUp(){
    menuPopup ? setMenuPopup(false) : setMenuPopup(true)
  }

  function ValidatingFirstName(value){
    if(!nameReg.test(value)){
      setFirstName("First name error. First Letter must be capital. Must use alphabets only")
      document.querySelector("div > h5").style.display = "block"
    } else {
      setFirstName(value)
      document.querySelector("div > h5").style.display = "none"
    }
  }

  function ValidatingLastName(value){
    if(!nameReg.test(value)){
      setLastName("Last name error. First Letter must be capital. Must use alphabets only")
      document.querySelector("div h5:nth-child(2)").style.display = "block"
    } else {
      setLastName(value)
      document.querySelector("div h5:nth-child(2)").style.display = "none"
    }
  }

  function ValidatingEmail(value){
    if(!emailReg.test(value)){
      setEmail("Email error")
      document.querySelector("div h5:nth-child(3)").style.display = "block"
      
    } else {
      setEmail(value)
      document.querySelector("div h5:nth-child(3)").style.display = "none"
    }
  }

  useEffect(()=>{
      if(emailReg.test(email) && nameReg.test(firstName) && nameReg.test(lastName)){
        setAppearButton(true)
      } else {
        setAppearButton(false)
      }
  })

  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="MDIA 2109"/>
        <meta property="og:title" content="Assignment #1 - Contact Us Page"/>
        <meta property="og:description" content="BCIT Digital Design and Development Diploma"/>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.mainContact}>
        <NavBar onClick={()=>{MenuPopUp(true)}}></NavBar>
        {menuPopup && <MenuProp onClick={()=>{MenuPopUp(false)}}></MenuProp>}
        <div className={styles.flexboxRowAbout}>
          <hr noshade="true" className={styles.lineBreakAbout}/>
          <h1 className={styles.h1About}>Contact Us</h1>
          <hr noshade="true" className={styles.lineBreakAbout}/>
        </div>
        <div>
          <p className={styles.contactP}>Want to discuss? Lets chat!</p>
        </div>
        <div>
          <form className={styles.form}>
            <fieldset>
              <table className={styles.table}>
                <thead>
                  <tr className={styles.flex}>
                    <th className={styles.tableHeader}>
                      <label>First Name:</label>
                      <input placeholder='First Name Here' className={styles.flex} type="text" onChange={(event)=>{ValidatingFirstName(event.target.value)}}></input>
                    </th>
                    <th className={styles.tableHeader}>
                      <label>Last Name:</label>
                      <input placeholder='Last Name Here' className={styles.flex} type="text" onChange={(event)=>{ValidatingLastName(event.target.value)}}></input>
                    </th>
                  </tr>
                </thead>
                <thead>
                  <tr>
                    <th className={styles.tableHeader} style={{width:"100%"}}>
                      <label>Email:</label>
                      <input placeholder='Email Here' style={{width:"100%"}} type="text" onChange={(event)=>{ValidatingEmail(event.target.value)}}></input>
                    </th>
                  </tr>
                </thead>
              </table>
            </fieldset>
            {appearButton && <a href='/' style={{marginTop:"20px"}}><button className={styles.borderWhiteButton} type="button">Submit</button></a>}
          </form>
        </div>
        <div className={styles.errorMessage}>
          <h5>{firstName}</h5>
          <h5>{lastName}</h5>
          <h5>{email}</h5>
        </div>
        
        
        <a href='/about'>
          <span>
            <img className={styles.downwardArrow} src="/upwardArrow.png"/>
          </span>
        </a>
        
        
      </main>
    </>
  )
}
